"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const common_1 = require("./common");
const cookie_1 = require("./cookie");
const date_1 = require("./date");
const device_1 = require("./device");
const dom_1 = require("./dom");
const regexp_1 = require("./regexp");
const string_1 = require("./string");
const url_1 = require("./url");
const package_json_1 = require("../package.json");
const saltireUtil = Object.assign({ name: package_json_1.name, version: package_json_1.version }, cookie_1.cookie, common_1.common, date_1.date, device_1.device, dom_1.dom, regexp_1.check, string_1.str, url_1.url);
exports.default = saltireUtil;
